### PR TITLE
Knshq reformatting 2

### PR DESCRIPTION
**Pull request by KNSHQ**

### CODE REVIEW

**Comment by Ninny659** [comment]
Running your branch, I immediately got a "Render Error". Please review comments made in render view, ensuring they are correctly formatted comments utilising React Native's proper methodology.

You can read more here:
https://github.com/airbnb/javascript/tree/master/react

A conflict also needs to be corrected before I can merge this into the main branch. If you fix what I have mentioned, I will be happy to review it again and see if everything works as expected.

**Review by Ninny659 — CHANGES_REQUESTED** [review]
Please review and fix errors that occur at run time.

**Comment by KNSHQ** [comment]
I have corrected the errors.

**Review by Ninny659 — CHANGES_REQUESTED** [review]
Changes to the EV database drawer and map have broken the popup menu of EV map pins. Please run and test the code thoroughly before submitting it for review.

**Comment by KNSHQ** [comment]
Fixed all known issues and tested the app for any potential problems.

**Pull request merged**
